### ISSUE TITLE
Styler breaks code when using <- in if-call

### ISSUE THREAD

**Issue by sebffischer** [r-lib/styler#886]
First of all, thank you for the great R package!

The bug that I am referring to is caused by styler.mlr, but I assume it is a general problem in styler. 
The reprex below describes the issue. 
Even though this might be bad practice I still think that it should not break otherwise running code. 

``` r
src = "if(a <- 1) print(a)"
eval(parse(text = src))
#> [1] 1
src_styled = styler.mlr::style_text(src, style = styler.mlr::mlr_style)
#> Error in parse(text = text, keep.source = TRUE): <text>:1:7: unexpected '='
#> 1: if (a =    
```

<sup>Created on 2021-12-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lorenzwalthert** [comment]
> The bug that I am referring to is caused by styler.mlr, but I assume it is a general problem in styler.

I don't think so. 

``` r
src = "if(a <- 1) print(a)"
eval(parse(text = src))
#> [1] 1
styler.mlr::style_text(src, style = styler::tidyverse_style)
#> if (a <- 1) print(a)
```

<sup>Created on 2021-12-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lorenzwalthert** [comment]
Let's re-open this in mlr-org/styer.mlr

**Comment by lorenzwalthert** [comment]
@sebffischer I closed it in {styler.mlr}. Thanks for reporting 👍.

**Comment by lorenzwalthert** [comment]
@sebffischer if you use pre-commit.ci, you might want to add the ref to the `.pre-commit-config.yaml` to not use a cached version of the {styler.mlr} package:
```yaml
    hooks:
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
        additional_dependencies:
        -    mlr-org/styler.mlr@aecf6e3
```
